export const veilAdsAbi = [
  {
    type: "function",
    name: "ATTENTION_MODE_FHE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "ATTENTION_THRESHOLD_SECONDS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "createCampaign",
    stateMutability: "payable",
    inputs: [
      {
        name: "targeting",
        type: "tuple[5]",
        components: [
          { name: "ctHash", type: "uint256" },
          { name: "securityZone", type: "uint8" },
          { name: "utype", type: "uint8" },
          { name: "signature", type: "bytes" },
        ],
      },
      {
        name: "maxBidInput",
        type: "tuple",
        components: [
          { name: "ctHash", type: "uint256" },
          { name: "securityZone", type: "uint8" },
          { name: "utype", type: "uint8" },
          { name: "signature", type: "bytes" },
        ],
      },
      { name: "adURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getCampaignCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getCampaignInfo",
    stateMutability: "view",
    inputs: [{ name: "campaignId", type: "uint256" }],
    outputs: [
      { name: "advertiser", type: "address" },
      { name: "escrow", type: "uint256" },
      { name: "active", type: "bool" },
      { name: "adURI", type: "string" },
    ],
  },
  {
    type: "function",
    name: "getMatchDetails",
    stateMutability: "view",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [
      { name: "user", type: "address" },
      { name: "winningCampaignId", type: "uint256" },
      { name: "clearingPriceWei", type: "uint256" },
      { name: "revealed", type: "bool" },
      { name: "attentionPassed", type: "bool" },
      { name: "paidOut", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "getMatchPriceHandle",
    stateMutability: "view",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getMatchResult",
    stateMutability: "view",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [
      { name: "revealed", type: "bool" },
      { name: "winningCampaignId", type: "uint256" },
      { name: "clearingPriceWei", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getMatchWinnerHandle",
    stateMutability: "view",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getAttentionHandle",
    stateMutability: "view",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "matchAd",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "profile",
        type: "tuple[5]",
        components: [
          { name: "ctHash", type: "uint256" },
          { name: "securityZone", type: "uint8" },
          { name: "utype", type: "uint8" },
          { name: "signature", type: "bytes" },
        ],
      },
    ],
    outputs: [{ name: "matchId", type: "uint256" }],
  },
  {
    type: "function",
    name: "claimPayout",
    stateMutability: "nonpayable",
    inputs: [{ name: "matchId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "submitReveal",
    stateMutability: "nonpayable",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "winnerId", type: "uint32" },
      { name: "winnerSig", type: "bytes" },
      { name: "clearingPrice", type: "uint128" },
      { name: "priceSig", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitEngagement",
    stateMutability: "nonpayable",
    inputs: [
      { name: "matchId", type: "uint256" },
      {
        name: "viewTimeSeconds",
        type: "tuple",
        components: [
          { name: "ctHash", type: "uint256" },
          { name: "securityZone", type: "uint8" },
          { name: "utype", type: "uint8" },
          { name: "signature", type: "bytes" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitAttentionResult",
    stateMutability: "nonpayable",
    inputs: [
      { name: "matchId", type: "uint256" },
      { name: "result", type: "bool" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "CampaignCreated",
    inputs: [
      { indexed: true, name: "campaignId", type: "uint256" },
      { indexed: true, name: "advertiser", type: "address" },
      { indexed: false, name: "adURI", type: "string" },
      { indexed: false, name: "escrow", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "MatchCreated",
    inputs: [
      { indexed: true, name: "matchId", type: "uint256" },
      { indexed: true, name: "user", type: "address" },
    ],
  },
] as const;
